[package]
name = "GORBIE"
description = "GORBIE! Is a minimalist notebook library for Rust."
version = "0.2.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
tribles = { git = "https://github.com/triblespace/tribles-rust" }
eframe = {version = "0.32 ", features = ["persistence", "wgpu"]}
egui = {version = "0.32", features=["color-hex"]}
egui_extras = "0.32.0"
parking_lot = { version = "0.12.3", features = ["arc_lock"] }
log = "0.4.26"
ctrlc = {version="3.4", features=["termination"]}
egui_commonmark = {version = "0.21", features = ["macros", "better_syntax_highlighting", "svg", "fetch"]}
image = { version = "0.25", features = ["png", "jpeg"] }
polars = "0.50.0"
egui-theme-switch = "0.4.0"

[features]
serde = []
accesskit = []
