[package]
name = "GORBIE"
description = "GORBIE! Is a minimalist notebook library for Rust."
version = "0.3.0"
edition = "2021"
authors = ["Jan-Paul Bultmann <jp@bultmann.eu>"]
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/gorbie"
homepage = "https://github.com/triblespace/GORBIE"
repository = "https://github.com/triblespace/GORBIE"
exclude = ["gorbie_commonmark"]

[dependencies]
gorbie-macros = { version = "0.2.1", path = "gorbie-macros" }
eframe = { version = "0.33", features = ["persistence", "wgpu"] }
egui = { version = "0.33", features = ["color-hex"] }
egui_extras = "0.33.0"
parking_lot = { version = "0.12.3", features = ["arc_lock"] }
log = "0.4.26"
ctrlc = {version="3.4", features=["termination"]}
egui_commonmark = { package = "gorbie-commonmark", version = "0.22.1", features = ["better_syntax_highlighting", "svg", "fetch"] }
image = { version = "0.25", features = ["png", "jpeg"] }
hifitime = "4.2.3"
polars = "0.50.0"
rapier2d = "0.18"
dark-light = "1"

[features]
serde = []
accesskit = []

[workspace]
members = ["gorbie-macros"]
exclude = ["gorbie_commonmark"]

[dev-dependencies]
ed25519-dalek = "2.1.1"
num-rational = "0.4.2"
rand = "0.8.5"
